import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import OverlaySidebar from "./components/OverlaySidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <OverlaySidebar />
        <main className="min-h-screen">{children}</main>
      </body>
    </html>
  );
}
